services:
  claude-engineer:
    build: .
    volumes:
      - ./workspace:/app/workspace
    env_file:
      - .env
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
      - FORCE_COLOR=1
    user: 1000:1000
    working_dir: /app
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL